version: "3"
services:
  ss:
    image: caogj/ss-client
    environment:
      - SERVER=${ss_ip}
      - SERVER_PORT=${ss_port}
      - PASSWORD=${ss_passwd}
      - LOCAL_PORT=1080
      - TIMEOUT=60
      - METHOD=aes-256-cfb
    restart: always
  proxy:
    image: caogj/polipo
    command:
      socksParentProxy=ss_server:1080
    ports:
      - "8123:8123"
    restart: always
    links:
      - "ss:ss_server"
